### ISSUE TITLE
submodules support

### ISSUE THREAD

**Issue by engilyin** [greensopinion/gradle-android-eclipse#4]
My project has multiple submodules. Some of them are git submodules(if it is important)
I tried this plugin as shown in the sample. It seemed to me I had to add suggested changes into each module's build.gradle not root project one. So it generates the .project and .classpath locally for each module. So eclipse does not see it.

I did not realize how can I make it generate other modules dependencies and how can I open the full project in Eclipse. Is it supported?

Also Eclipse has the gradle support now days. It would be nice if the changes could be made for the root project build.gradle and plugin will find all project dependencies and generate eclipse gradle project. So it will work in eclipse right form the box.

**Comment by greensopinion** [comment]
Thanks for the suggestions.  

This project doesn't handle your use-case at all, and since it's an extension of the [Gradle eclipse plugin](https://docs.gradle.org/current/userguide/eclipse_plugin.html), what you're looking for would likely have to be supported there first.

I'm sorry but I won't be looking into this further. Feel free to fork this repo and make changes there to suit your needs.

**Comment by engilyin** [comment]
Ok. Thank you anyway.
